{
 "title": "Fetch-Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total of user_login Records Processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(record_type, topic) (total_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Logins By Device Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(topic, device_type) (device_type_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UserLogins For Locale",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(locale, topic) (locale_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic:user_login RateOfMessagesInPerSec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(kafka_BrokerTopicMetrics_MessagesInPerSec_topic_user_login{instance=\"kafka:9998\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic:user-login_analytics RateOfMessagesInPerSec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(kafka_BrokerTopicMetrics_MessagesInPerSec_topic_user_login_analytics{instance=\"kafka:9998\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}